/**
 * @packageDocumentation
 * @module api.functional.ping
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @summary Пингуем сервис.
 * @returns pong
 * @controller AppController.getPing
 * @path GET /ping
 * @accessor api.functional.ping.getPing
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPing(
  connection: IConnection,
): Promise<getPing.Output> {
  return PlainFetcher.fetch(connection, {
    ...getPing.METADATA,
    template: getPing.METADATA.path,
    path: getPing.path(),
  });
}
export namespace getPing {
  export type Output = Primitive<string>;

  export const METADATA = {
    method: "GET",
    path: "/ping",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ping";
}
